"""One display vocabulary: the team's word for every field, in one place.

The register a colleague already keeps is a workbook, and its column headings are
the words the team uses when it talks about a tender. Those words are not TED's.
TED says *buyer*; the team says *client*. TED says *country of performance*; the
team says *project location*. A second source will say something different again,
and the moment two surfaces name the same fact differently the register stops
being one register.

So every place a field is named to a human - the detail page, the table headers,
the export columns, the API descriptions - reads its label from here.

Two rules hold this together:

- **The key is plumbing and never changes.** ``client`` is a stable identifier
  used in stored extractions, in export headers and in URLs. Changing a label is
  a one-line edit here; changing a key is a data migration.
- **A label is never a database column name.** Nothing here renames a column on
  ``TenderRow`` or a field on ``Tender``. The internal names stay exactly as they
  are; this module only decides what a person is shown.

Each field also declares two things the page has to be able to say. :class:`Group`
is which half of the register it belongs to - what the documents say, or what
Entr's own analysis concluded. :class:`Provenance` is where a value came from,
which is the distinction the whole tool rests on: a source fact, a document
extract, Watchdog's own intelligence, or a colleague's judgement. A field whose
origin varies between notices declares the origin it *can* have and the display
layer states the one it actually had.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class Provenance(StrEnum):
    """Where one value came from. Four kinds, never blurred into each other."""

    # Stated by the publishing platform's API.
    SOURCE = "source"
    # Read out of a notice or an attachment.
    DOCUMENT = "document"
    # Produced by Watchdog - a rule or a model. A judgement, not a fact.
    ASSESSMENT = "assessment"
    # Recorded by a colleague.
    REVIEW = "review"


PROVENANCE_LABELS: dict[Provenance, str] = {
    Provenance.SOURCE: "From the platform's API",
    Provenance.DOCUMENT: "Extracted from a document",
    Provenance.ASSESSMENT: "Generated by assessment",
    Provenance.REVIEW: "Recorded by a colleague",
}


class Group(StrEnum):
    """The two halves of the register, as the workbook lays them out."""

    DOCUMENTS = "documents"
    ANALYSIS = "analysis"


GROUP_LABELS: dict[Group, str] = {
    Group.DOCUMENTS: "From the documents",
    Group.ANALYSIS: "Entr AI analysis",
}

GROUP_NOTES: dict[Group, str] = {
    Group.DOCUMENTS: (
        "Stated by the publishing platform or read out of the notice. Nothing here is "
        "Watchdog's opinion."
    ),
    Group.ANALYSIS: (
        "Watchdog's own judgement, with the evidence it rests on. Never presented as "
        "something the buyer said."
    ),
}


@dataclass(frozen=True)
class FieldSpec:
    """One register field: its stable key, the team's word for it, and what it is."""

    key: str
    label: str
    group: Group
    # The origin a value of this field can have. Where a field can be stated by
    # the source *or* inferred, this is the weaker of the two and the display
    # layer states which one actually applied.
    provenance: Provenance
    # Shown above the fold. Everything else folds into "More details".
    prominent: bool = False
    # One sentence for a colleague, where the label alone would mislead.
    note: str | None = None
    # True when nothing in a source API can fill this field, so it can only ever
    # arrive from reading a document. These are the keys a stored extraction may
    # use, and the only ones; see FIELDS_EXTRACTED.
    extracted: bool = False


# Every field, in the order the workbook lists them. The page groups them without
# reordering, so a colleague reading down the page reads down their own register.
FIELDS: tuple[FieldSpec, ...] = (
    FieldSpec(
        key="tender_name",
        label="Tender Name",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        prominent=True,
    ),
    FieldSpec(
        key="client",
        label="Client",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        prominent=True,
        note="Who is buying. Not necessarily who the work is for.",
    ),
    FieldSpec(
        key="client_country",
        label="Client Country",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        prominent=True,
    ),
    FieldSpec(
        key="project_location",
        label="Project Location",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        prominent=True,
        note="Where the work happens. A different question from who is buying.",
    ),
    FieldSpec(
        key="published_date",
        label="Published Date",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        prominent=True,
    ),
    FieldSpec(
        key="deadline_date",
        label="Deadline Date",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        prominent=True,
    ),
    FieldSpec(
        key="public_platform",
        label="Public Platform",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        note=(
            "Where the notice was published. Not the bidding portal and not the "
            "document links, which are listed separately."
        ),
    ),
    FieldSpec(
        key="phase_of_tender",
        label="Phase of Tender",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        note="Which step of the procurement this notice is.",
    ),
    FieldSpec(
        key="phase_of_project",
        label="Phase of Project",
        group=Group.ANALYSIS,
        # A notice sometimes says this outright. More often it does not, and then
        # it is a model's reading of the text. The display states which happened;
        # see services.summary.
        provenance=Provenance.ASSESSMENT,
        note="How far the buyer's own project has travelled towards a commitment.",
    ),
    FieldSpec(
        key="scope_of_work_technical",
        label="Scope of Work (Technical)",
        group=Group.ANALYSIS,
        provenance=Provenance.ASSESSMENT,
        extracted=True,
    ),
    FieldSpec(
        key="scope_of_work_commercial",
        label="Scope of Work (Commercial)",
        group=Group.ANALYSIS,
        provenance=Provenance.ASSESSMENT,
        extracted=True,
    ),
    FieldSpec(
        key="duration",
        label="Duration",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
    ),
    FieldSpec(
        key="budget_and_commercial_model",
        label="Budget and Commercial Model",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        note="Money keeps its currency. Nothing is converted and nothing is summed.",
    ),
    FieldSpec(
        key="professional_indemnity_requirement",
        label="Professional Indemnity Requirement",
        group=Group.DOCUMENTS,
        provenance=Provenance.DOCUMENT,
        extracted=True,
    ),
    FieldSpec(
        key="local_content_requirement",
        label="Local Content / Presence Requirement",
        group=Group.DOCUMENTS,
        provenance=Provenance.DOCUMENT,
        extracted=True,
    ),
    FieldSpec(
        key="site_visit_requirement",
        label="Site Visit Requirement",
        group=Group.DOCUMENTS,
        provenance=Provenance.DOCUMENT,
        extracted=True,
    ),
    FieldSpec(
        key="submission_language",
        label="Submission language",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        note=(
            "The language a bid may be written in. It establishes nothing about the "
            "working language or the language of the team, and it is not the language "
            "the notice was published in."
        ),
    ),
    FieldSpec(
        key="team_composition_requirement",
        label="Team Composition Requirement",
        group=Group.DOCUMENTS,
        provenance=Provenance.DOCUMENT,
        extracted=True,
    ),
    FieldSpec(
        key="experience_qualification_requirement",
        label="Experience & Qualification Requirement",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
        note="The qualification bar, as the notice states it.",
    ),
    FieldSpec(
        key="evaluation_and_award_criteria",
        label="Evaluation Methodology & Award Criteria",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
    ),
    FieldSpec(
        key="procurement_documents_link",
        label="Procurement Documents Link",
        group=Group.DOCUMENTS,
        provenance=Provenance.SOURCE,
    ),
    FieldSpec(
        key="documents_likely_required",
        label="Documents Likely Required for Submission",
        group=Group.ANALYSIS,
        provenance=Provenance.ASSESSMENT,
        extracted=True,
    ),
)

BY_KEY: dict[str, FieldSpec] = {spec.key: spec for spec in FIELDS}

# The keys a stored extraction may use. Pinning this list is what closes
# docs/decisions/0001: a field renamed in a prompt is now an error on the way in
# rather than a blank on the page that looks like "the notice did not say".
FIELDS_EXTRACTED: tuple[str, ...] = tuple(spec.key for spec in FIELDS if spec.extracted)


def label(key: str) -> str:
    """The team's word for a field. Falls back to the key rather than inventing one."""
    spec = BY_KEY.get(key)
    return spec.label if spec is not None else key


def spec(key: str) -> FieldSpec | None:
    return BY_KEY.get(key)


def in_group(group: Group) -> tuple[FieldSpec, ...]:
    """Every field of one group, in workbook order."""
    return tuple(item for item in FIELDS if item.group is group)


def provenance_label(origin: Provenance) -> str:
    return PROVENANCE_LABELS[origin]


def group_label(group: Group) -> str:
    return GROUP_LABELS[group]
